[[fh-sync-connect]]
== $fh.sync.connect

Make sure the sync server is connected to the requried dependent resources, like MongoDB and Redis.

NOTE: You don't need to invoke this if you are using the fh-mbaas-api module in your app, it will be called automatically.

=== Usage

[source,javascript]
----
$fh.sync.connect(mongodbConnectionString, mongodbConf, redisConnectionString, callback)
----

=== Parameters

==== mongodbConnectionString
* Description: The connection url of MongoDB
* Type: String

==== mongodbConf
* Description: The MongoDB connection options. For more details of this option, please check http://mongodb.github.io/node-mongodb-native/2.1/api/MongoClient.html[MongoClient.connect API doc].
+
As mentioned above, in most cases you don't need to call this function. 
However, you can still control some of the MongoDB connection options via environment variables:
+
** SYNC_MONGODB_POOLSIZE
*** Description: Specify the MongoDB connection pool size
*** Type: Number
*** Default: 50
* Type: Object

==== redisConnectionString
* Description: The connection url of Redis. Should include authentication info if required.
* Type: String

==== callback
* Description: the callback function
* Type: function

=== Example

[source,javascript]
----
var mongodbUrl = "mongodb://mongouser:mongopass@127.0.0.1";
var redisUrl = "redis://redisuser:redispass@127.0.0.1";

$fh.sync.connect(mongodbUrl, {}, redisUrl, function(err){
  if (err) {
    console.error('Connection error for sync', err);
  } else {
    console.log('sync connected');
  }
});
----