[[fh-sync-globalhandledelete]]
== $fh.sync.globalHandleDelete

Defines a global handler function for deleting a single row of data from the back end.

It can be used by multiple datasets, but will only be used if there is no handler assigned to the dataset via the link:./handleDelete.adoc[handleDelete API].

The sync server will make sure the data can be deleted. I.e. the data to be deleted is up to date and will not cause collisions.

=== Usage

[source,javascript]
----
$fh.sync.globalHandleDelete(function deleteHandler(dataset_id, uid, meta_data, cb){});
----

=== Parameters

==== deleteHandler
* Description: The function that will be invoked when deleting a record.
* Type: Function
* Invoked Parameters:
** *dataset_id*
*** Description: the id of the dataset
*** Type: String
** *uid*
*** Description: the unique id of the record that should be deleted
*** Type: String
** *meta_data*
*** Description: the meta data associated with the data. Could be null.
*** Type: Object
** *cb*
*** Description: the callback function
*** Type: Function

=== Example

[source,javascript]
----
$fh.sync.globalHandleDelete(function(dataset_id, uid, meta_data, cb) {
  // The dataset identifier that this function was defined for
  console.log(dataset_id);

  // Unique Identifier for row to update
  console.log(uid);

  // Sample back-end storage call
  var deletedData = deleteData(uid);

  /* sample response
    {
      "userid": "1234",
      "name": "Jane Bloggs",
      "age": 27
    }
  */

  // The callback into the sync service to return the deleted row of data
  return cb(null, deletedData);
});
----